### ISSUE TITLE
Branch selection

### ISSUE THREAD

**Issue by rodylg** [Forevener/DRPGSEL#1]
Consider supporting the WNC12k/DoomRPG-Rebalance fork.

**Comment by Forevener** [comment]
Will be done soon.

**Comment by Forevener** [comment]
Please test the new release.

**Comment by WNC12k** [comment]
Thank you for support. However for some reason patches are not connected. I mean like "Doom RPG/Doom RPG-R L Arsenal". In version 1.0.3 there is no such problem, as patches can be enabled manually. Could you fix this? Thanks!

**Comment by Forevener** [comment]
You are welcome!
They are not connecting because DRPGINFO.txt of the patch was not updated with the mod's filename. 
For now you could fix that by either adding the patch to the custom command line or changing the "Mods=" entry in the DRPGINFO.txt in DoomRPG-RLArsenal folder.
