### ISSUE TITLE
DRPG Pandemonia Monsters pacth broke laucher config

### ISSUE THREAD

**Issue by RonDallas** [Forevener/DRPGSEL#10]
We update a new comparability path for Pandemonia Monsters and after i close a launcher - he is ded.
Some screenshots:
![зображення](https://user-images.githubusercontent.com/32035822/189701524-f2f9beac-7ca3-426f-be37-646b6163e39c.png)
![зображення](https://user-images.githubusercontent.com/32035822/189701100-3c245946-4f35-4535-80dd-a82c043c5df5.png)
![зображення](https://user-images.githubusercontent.com/32035822/189701199-326f6a08-8995-4b63-b61f-58463d62cf44.png)
![зображення](https://user-images.githubusercontent.com/32035822/189701236-f628ebee-8519-4f3f-b952-bc4e97e0d705.png)

**Comment by RonDallas** [comment]
Also its not on mod filename. If i save config with only mod file cheked - launcher is work

**Comment by Forevener** [comment]
Should be fixed now, please take a look.

**Comment by RonDallas** [comment]
Its work now. Thanks)
