### ISSUE TITLE
Rename your .WAD files to .wad before using them, the launcher doesn't recognize .WAD on caps

### ISSUE THREAD

**Issue by GuyFromGitTheHub** [Forevener/DRPGSEL#12]
for some reason, the launcher doesn't support .WAD files if the .wad part is on caps, and maybe it does the same with .pk3, fix this, i know it is as easy as renaming them to .wad instead of .WAD, but what if someone doesn't get it and gives up? it can happen.

**Comment by GuyFromGitTheHub** [comment]
almost forgot to add, that's on version 1.3.1

**Comment by Forevener** [comment]
Yeah, it is a very silly bug. Please check if it is fixed in the newest release 1.3.2.1

**Comment by GuyFromGitTheHub** [comment]
thanks
