### ISSUE TITLE
Doom RLArsenal fatal error; not loading

### ISSUE THREAD

**Issue by devlman127** [Forevener/DRPGSEL#2]
If I try to load Doom RLArsenal I get this error:

> Script warning, ":textures.txt" line 16:
Unknown patch 'MA75X0' in texture 'MA75Y0'
>Script warning, ":textures.txt" line 23:
Unknown patch 'WSTEX0' in texture 'WSTEY0'
>ANIMDEFS: Can't find PMARA1
>Execution could not continue.
>Script error, ":animdefs.txt" line 7:
>Unknown texture PMARA1

I checked the folder and I see that it doesn't contain the entirety of what it needs. Do I need to extract the latest version of DRLA into the folder and let the folder files override it or what?

**Comment by Forevener** [comment]
Interesting - this error usually appears when user applies DRLA patch while not having DRLA itself. But DRPGSEL enables patches automatically, so that shouldn't happen. Please show your load order and also DRPGSEL command-line.

**Comment by devlman127** [comment]
I've enabled the standalone mods and it seems to work fine now and shows the entire DRLA weapon selection in the shop. However, the DRLA statusbar HUD does not show up, I'm not planning on using it but it seems prudent to note.

**Comment by Forevener** [comment]
As far as I remember, DRLA HUD is included in the main DRLA package, so this probably related to DRPG, not to the load order.
