### ISSUE TITLE
[v1.2.0] Selecting fork does not change source

### ISSUE THREAD

**Issue by FelesNoctis** [Forevener/DRPGSEL#3]
As title. I created separate configurations for DRPG-SE and DRPG-Rebalanced and attempted to download each to different folders. After several rounds of deleting and redownloading, checking settings multiple times, restarting the launcher at different steps, clean uninstalling and reinstalling the launcher to attempt only a Rebalanced version (and yes, making sure to click Save for the profile preset), as far as my tests went, the launcher would _**only**_ download **Sumwunn/DoomRPG**.

During update process: https://i.imgur.com/AMhUGa7.png
That should be "DoomRPG-Rebalance-master" if all's going right.

**Comment by FelesNoctis** [comment]
I'm assuming this is related, so I'm adding it here as well.

In addition to the above, attempting to select the "Test" branch of **WNC12k/DoomRPG-Rebalance** causes a CTD. My guess would be because that branch doesn't exist on **Sumwunn/DoomRPG**, since branch selection **_does_** work on Sumwunn's repo.

**Comment by Forevener** [comment]
Thank you for such well-described issue, your observation is, in fact, correct! I forgot to change the main URI and launcher was trying to download everything from Sumwunn's fork. Please test the new version.

**Comment by FelesNoctis** [comment]
Looks like that did the trick! I tested with WNC12k/DoomRPG-Rebalance-master, WNC12k/DoomRPG-Rebalance-test, and Sumwunn/DoomRPG-experimental, and everything seems to have downloaded correctly!

However, 1.2.1 seems to have added a new quirk. After a download of a fork/branch, both the fork and branch selection dropdown menus will be greyed out and unresponsive. Switching the profile will reenable the branch menu becomes usable, but fork is still locked. As far as I can tell the only way to reenable fork is to restart the launcher.

1.2.1 Post-Download: https://i.imgur.com/C4KnASR.png
1.2.1 After Profile Swap: https://i.imgur.com/eFf6EOD.png
1.2.0 Post-Download: https://i.imgur.com/RiE4tkJ.png

**Comment by Forevener** [comment]
Your reports are really masterful!
Yes, fork/branch selection should not be available during the download. I should have incorporated that back in 1.2.0, haven't thought about it, incorporated in 1.2.1 and forgot to make them available after download. Welp, haste makes waste I presume...
Please check the new release.

**Comment by FelesNoctis** [comment]
Looks good! In 1.2.2 the fork and branch controls reenabled themselves after a download.

Yeah, don't you love it when you have a great idea and then there's that *one* small thing you overlook? And hey, if you like my reports, I'm sure I can find ways to keep you busy! 😄

**Comment by Forevener** [comment]
Hah, most certainly! This happens sometimes...
Well then, if you can keep reports coming, please do! I'm always happy to improve things I'm making.
