### ISSUE TITLE
Mismatching Between Launcher and In-Game Difficulties

### ISSUE THREAD

**Issue by DistinctSoul** [Forevener/DRPGSEL#5]
At first, this wasn't really an issue, as it was just the names of the difficulties being slightly different (such as Hell being called Technophobia in-game), and the Adaptive difficulty being in a different position than it was in the game. Now however, I believe due to an update WNC12K has released recently, the list of difficulties in the launcher now directly correlate to the positions they would be in-game. For instance, as Adaptive is at the bottom of the list in the launcher, being the 7th one down; now when starting the game on that difficulty through the launcher, this will actually put you on the Technophobia difficulty in-game, as that is the 7th difficulty in the list when in the game's menu. Similarly, if you were to select Easy difficulty, you would actually start the game on Very Easy - which isn't actually on the list.

Imo, I do see why Adaptive is at the bottom, because it's a unique difficulty which gets harder the more you play. However, I do find it would be more appropriate if it was in the same position as it was in-game; not because of just that, but because the difficulty starts on Ultra-Violence, which is between Standard and Nightmare.

**Comment by Forevener** [comment]
Latest version includes reordered DRLA difficulties now. Please check it out.
