### ISSUE TITLE
A "Steam" error

### ISSUE THREAD

**Issue by RonDallas** [Forevener/DRPGSEL#7]
So i have this thing when i start a game
![зображення](https://user-images.githubusercontent.com/32035822/188548399-1d6e5961-1582-400a-bcd1-7b1a64c6a2b7.png)

**Comment by RonDallas** [comment]
Win7 (gzdoom 4.8.2, it just folder name)

**Comment by WNC12k** [comment]
here's another screenshot, from another user from Discord:
![IMG20220906111954](https://user-images.githubusercontent.com/40601544/188623790-fe0a8b75-0a04-4389-a0f5-06c40ad0d79b.jpg)

**Comment by WNC12k** [comment]
where does SteamLibrary come from ?

the user claims that it has no Steam

**Comment by Forevener** [comment]
1) The error seems related to the lack of branch in the appropriate selector, but it should have been downloaded almost immediately. Was you Internet connection OK? I made a hotfix (1.3.1.1) which should make the launcher work properly even without branch selected, please give it a try.
2) The error makes it look like you don't have the file selected as GZdoom path (it doesn't exist or something). The info from 'Show command line' could shed some light on this problem.

The mention of my working folder in exceptions is surprising, to say the least.

**Comment by WNC12k** [comment]
Discord user reports that this did not help. Any other options?

**Comment by RonDallas** [comment]
Ok, 1.3.1.1 is work well. Except branch download. But there is open another issue
