### ISSUE TITLE
Unable to select a branch

### ISSUE THREAD

**Issue by WNC12k** [Forevener/DRPGSEL#8]
Unable to select a branch
![unknown](https://user-images.githubusercontent.com/40601544/188701898-c1637cc1-5855-4fe4-b9d9-b3bb0976641d.png)

**Comment by WNC12k** [comment]
Internet is fine

**Comment by Forevener** [comment]
Should be fixed in 1.3.1.2, please give it a try.

**Comment by RonDallas** [comment]
In DoomRPG SE Launcher v1.3.1 hotfix 2 fixed. Thanks)
