### ISSUE TITLE
DoomRPG in the Load Order

### ISSUE THREAD

**Issue by WNC12k** [Forevener/DRPGSEL#9]
![1](https://user-images.githubusercontent.com/40601544/188704078-8b5d6ab4-4291-4746-a0be-1f9f454f02c1.PNG)

Now through the Launcher you can run DoomRPG, although it is highlighted in yellow.

Can we make it impossible to launch it until the user correctly sets the order with DoomRPG?

**Comment by WNC12k** [comment]
Or as an option to make it automatically take the order after mods and before patches?

Reason: to relieve the user's headache

**Comment by WNC12k** [comment]
I understand that this can be technically challenging and cause even more bugs. In that case, it will be enough if it stands out in red and not let the game run.

**Comment by Forevener** [comment]
Please take a look at the new version.
